/* NEXORA - Tailwind config (loaded BEFORE cdn.tailwindcss.com) */
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary-fixed-variant": "#3323cc",
                "on-secondary-container": "#64636d",
                "tertiary": "#5c00ca",
                "surface": "#f9f9ff",
                "outline": "#777587",
                "on-tertiary-container": "#e4d4ff",
                "error-container": "#ffdad6",
                "tertiary-fixed": "#eaddff",
                "on-primary-fixed": "#0f0069",
                "surface-container-low": "#f0f3ff",
                "on-tertiary-fixed-variant": "#5a00c6",
                "on-background": "#111c2d",
                "on-primary": "#ffffff",
                "surface-container": "#e7eeff",
                "surface-container-high": "#dee8ff",
                "outline-variant": "#c7c4d8",
                "primary-fixed": "#e2dfff",
                "inverse-on-surface": "#ecf1ff",
                "primary-container": "#4f46e5",
                "secondary-fixed": "#e3e1ed",
                "surface-container-lowest": "#ffffff",
                "background": "#f9f9ff",
                "on-surface": "#111c2d",
                "primary": "#3525cd",
                "tertiary-container": "#7531e6",
                "primary-fixed-dim": "#c3c0ff",
                "surface-tint": "#4d44e3",
                "secondary-fixed-dim": "#c7c5d1",
                "on-surface-variant": "#464555",
                "inverse-surface": "#263143",
                "surface-bright": "#f9f9ff",
                "secondary": "#5d5d67",
                "error": "#ba1a1a",
                "on-error-container": "#93000a",
                "on-primary-container": "#dad7ff",
                "on-secondary-fixed-variant": "#46464f",
                "tertiary-fixed-dim": "#d2bbff",
                "surface-container-highest": "#d8e3fb",
                "on-secondary-fixed": "#1a1b23",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "surface-dim": "#cfdaf2",
                "on-error": "#ffffff",
                "on-tertiary-fixed": "#25005a",
                "secondary-container": "#e3e1ed",
                "inverse-primary": "#c3c0ff",
                "surface-variant": "#d8e3fb"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "unit": "4px",
                "container-max": "1280px",
                "stack-sm": "8px",
                "stack-md": "16px",
                "stack-lg": "32px",
                "margin-mobile": "16px",
                "gutter": "24px",
                "margin-desktop": "40px"
            },
            "fontFamily": {
                "headline-lg": ["Be Vietnam Pro"],
                "body-md": ["Inter"],
                "label-md": ["Inter"],
                "headline-md": ["Be Vietnam Pro"],
                "display": ["Be Vietnam Pro"],
                "label-sm": ["Inter"],
                "body-lg": ["Inter"],
                "headline-lg-mobile": ["Be Vietnam Pro"]
            },
            "fontSize": {
                "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
                "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }]
            }
        },
    },
};
